# WEEK 1: BASIC LINEAR ALGEBRA EXCERCISE IN PYTHON

In [ ]:
NAME:SARANYA S
ROLL NO:235229134

# Exercise :1

In [1]:
import numpy as np
a=np.array([[1,2],[1,3]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print('matrix c=a*b*')
print(c)

matrix c=a*b*
[[19 22]
 [26 30]]


# Exercise :2

In [5]:
import numpy as np
a = np.array([[4, 2], [1, 3]])
eigen_values, eigen_vectors = np.linalg.eig(a)
print("Eigen values:")
print(eigen_values)
print("Eigen vectors:")
print(eigen_vectors)

Eigen values:
[5. 2.]
Eigen vectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Exercise :3

In [10]:
import numpy as np
a=np.array([[3,2,2],[2,3,-2]])
u,s,v=np.linalg.svd(a)
print("Singular values (s):")
print(s)
print("Right singular vectors (v):")
print(v)

Singular values (s):
[5. 3.]
Right singular vectors (v):
[[-7.07106781e-01 -7.07106781e-01 -5.55111512e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


# Exercise :4

In [11]:
import numpy as np
a=np.array([[6,1],[2,3]])
det = np.linalg.det(a)
print("Determinant of v:")
print(det)

Determinant of v:
15.999999999999998


# Exercise :5

In [13]:
import numpy as np
v=np.array([3,4])
l1_norm=np.linalg.norm(v,ord=1)
l2_norm=np.linalg.norm(v)
print(l1_norm)
print(l2_norm)

7.0
5.0
